# Generated by Django 5.2.6 on 2026-07-04 23:18

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_category_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                max_length=500,
                upload_to="products/",
                validators=[products.models.validate_image_upload_or_url],
            ),
        ),
    ]
